### ISSUE TITLE
cannot update with auto update

### ISSUE THREAD

**Issue by sconnery** [linuxserver/docker-ombi#42] opened 2019-01-15 12:54 UTC
3.0.4036
--

[lin  at Ombi.Schedule.Jobs.Ombi.OmbiAutomaticUpdater.Update(PerformContext c) in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Ombi\OmbiAutomaticUpdater.c
ne 239                                                                                                                                                   
fail: Ombi.Schedule.Jobs.Ombi.OmbiAutomaticUpdater[0]                                                                                                    
      Exception thrown in the OmbiUpdater, see previous messages                                                                                         
System.ComponentModel.Win32Exception (2): No such file or directory                                                                                      
   at Interop.Sys.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean re
ctStderr, Boolean setUser, UInt32 userId, UInt32 groupId, Int32& lpChildPid, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean shouldThrow)      
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)                                                                                   
   at System.Diagnostics.Process.Start()                                                                                                                 
   at Ombi.Schedule.Jobs.Ombi.OmbiAutomaticUpdater.Update(PerformContext c) in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Ombi\OmbiAutomaticUpdater.c
ne 239      uxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

**Comment by aptalca** [comment] 2019-01-15 12:58
Duplicate of #36

**Closed by aptalca** 2019-01-15 12:58 UTC
